import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Dev Detective",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={spaceMono.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
